.TH make-aspkg 1 "May 2017" "" "Android Studio Packer"

.SH NAME
\fBmake-aspkg\fP - Builds Debian package from Android Studio binary distribution

.SH SYNOPSIS
.nf
.fam C
\fBmake-aspkg\fP [\fIFILE\fR]
.fam T
.fi

.SH DESCRIPTION
\fBmake-aspkg\fP builds a Debian package from the given Android Studio binary distribution FILE.
.br
Download the Android Studio IDE from \fBhttps://developer.android.com/studio/index.html\fP and execute \fBmake-aspkg\fP \fIFILE\fR with the downloaded file. The Debian package is built in the current directory.
.br
The program requires about 1 GB free disk space in a temporary directory. The default directory is \fI/tmp\fR but you can change it by setting the environment variable \fITMPDIR\fR.

.SH EXAMPLE
After you downloaded Android Studio IDE from the website you need just to invoke make-aspkg to build the Debian package:

    make-aspkg /path/to/directory/android-studio-ide-123.4567890-linux.zip

This generates a Debian package in the current directory. It takes some time! After it has finished the resulting package can be installed with:

    dpkg -i android-studio_2.3_amd64.deb

When finished the Debian package and the downloaded ZIP file can be removed.

.SH AUTHOR
Philipp Meisberger <team@pm-codeworks.de>

Please send bug reports to this mail address. Visit http://www.pm-codeworks.de for more interesting projects.
