language: bash
sudo: required

env:
  global:
    - ANDROID_STUDIO_VERSION=3.4.2.0
    - ANDROID_STUDIO_FILE=android-studio-ide-183.5692245-linux.tar.gz

before_install:
  - sudo apt-get update
  - sudo apt-get install -y debhelper devscripts fakeroot

install:
  - dpkg-buildpackage -uc -us
  - sudo dpkg -i ../android-studio-package*.deb

script:
  - wget https://dl.google.com/dl/android/studio/ide-zips/${ANDROID_STUDIO_VERSION}/${ANDROID_STUDIO_FILE}
  - travis_wait make-aspkg ${ANDROID_STUDIO_FILE}

notifications:
  email:
    on_success: change
    on_failure: change
