#!/bin/sh
VERSION='1.0'

## Parse optional arguments
if [ "${1}" = "--version" ]; then
    echo "$(basename "${0}") ${VERSION}"
    exit 0
elif [ "${1}" = "--help" ]; then
    echo "Usage: $(basename "${0}") [OPTION] FILE"
    echo ""
    echo "Builds Debian package from Android Studio binary distribution"
    echo ""
    echo "Options:"
    echo ""
    echo "--help       Display this help message and exit"
    echo "--version    Print version information and exit"
    exit 0
fi

## Parse FILE argument
if [ -z "${1}" ]; then
    echo "Error: Missing FILE argument!"
    exit 1
elif [ ! -e "${1}" ]; then
    echo "Error: The file \"${1}\" does not exist!"
    exit 1
elif [ ! -r "${1}" ]; then
    echo "Error: The file \"${1}\" is not readable!"
    exit 1
fi

## Try to use environment variable TMPDIR
if [ -z "${TMPDIR}" ]; then
    TEMP_DIR="/tmp"
else
    TEMP_DIR="${TMPDIR}"
fi

PACKAGE_ROOT_DIR="${TEMP_DIR}/android-studio-package"
PACKAGE_LIB_DIR="${PACKAGE_ROOT_DIR}/usr/lib"
PACKAGE_AS_DIR="${PACKAGE_LIB_DIR}/android-studio"
CURRENT_DIR="$(pwd)"

## Extract Android Studio in "lib" directory
mkdir -p "${PACKAGE_LIB_DIR}"
unzip "${1}" -d "${PACKAGE_LIB_DIR}"

## Use system JRE
rm -rf "${PACKAGE_AS_DIR}/jre/"

## Copy Debian package files
mkdir "${PACKAGE_ROOT_DIR}/debian/"
cp -R /usr/share/android-studio-package/debian "${PACKAGE_ROOT_DIR}"

## Copy copyright file
cp "${PACKAGE_AS_DIR}/LICENSE.txt" "${PACKAGE_ROOT_DIR}/debian/copyright"

## Insert maintainer name in control file
if [ -n "${DEBFULLNAME}" ]; then
    MAINTAINER_NAME=${DEBFULLNAME}
else
    MAINTAINER_NAME="$(getent passwd $(whoami) | cut -d ':' -f 5 | cut -d, -f 1)"
fi

sed -i "s/MAINTAINER_NAME/${MAINTAINER_NAME}/" "${PACKAGE_ROOT_DIR}/debian/control"

## Insert maintainer mail in control file
if [ -n "${DEBEMAIL}" ]; then
    MAINTAINER_MAIL=${DEBEMAIL}
else
    MAINTAINER_MAIL="$(whoami)@$(hostname --fqdn )"
fi

sed -i "s/MAINTAINER_MAIL/${MAINTAINER_MAIL}/" ${PACKAGE_ROOT_DIR}/debian/control

## Extract version
ANDROID_STUDIO_VERSION="$(basename "${1}" | cut -d '-' -f 4)"

## Create changelog
cd ${PACKAGE_ROOT_DIR}
dch --create --package android-studio -v "${ANDROID_STUDIO_VERSION}" "This package was automatically created by android-studio-package."
dch --release ""

## Build the package (binary only)
fakeroot debian/rules binary
mv ../android-studio_*.deb "${CURRENT_DIR}/"

## Clean up
cd ..
rm -rf "${PACKAGE_ROOT_DIR}"
exit 0
